# Generated by Django 4.2.3 on 2023-11-08 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectrequest',
            name='user_id',
        ),
        migrations.AddField(
            model_name='projectrequest',
            name='cleint_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='client.client'),
        ),
    ]
