# Generated by Django 4.2.3 on 2023-11-14 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_project_documents'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectterms',
            name='project_docs',
        ),
    ]
