# Generated by Django 4.2.3 on 2023-11-06 03:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('date', models.DateField(auto_now_add=True)),
                ('tag', models.CharField(max_length=255)),
                ('portrait_format', models.CharField(default='square', max_length=50)),
                ('private', models.BooleanField(default=False)),
                ('display', models.CharField(choices=[('none', 'none'), ('home', 'home'), ('IOTM', 'IOTM'), ('model', 'model'), ('wedding', 'wedding'), ('family', 'family'), ('modelgal', 'modelgal'), ('weddinggal', 'weddinggal'), ('familygal', 'familygal'), ('project', 'project'), ('project-header', 'project-header')], default='none', max_length=20)),
                ('image_link', models.URLField(blank=True, default=' ')),
                ('cloudflare_id', models.CharField(blank=True, max_length=255)),
                ('silk_id', models.CharField(default='CB01', max_length=50)),
                ('client_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='client.client')),
                ('project_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='client.project')),
            ],
        ),
    ]
