# Generated by Django 4.2.3 on 2023-11-22 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dispaly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='image',
            name='display',
        ),
        migrations.AddField(
            model_name='image',
            name='display',
            field=models.ManyToManyField(to='gallery.dispaly'),
        ),
    ]
