# Generated by Django 4.2.3 on 2023-11-12 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('file_path', models.CharField(max_length=255)),
                ('doc_type', models.CharField(blank=True, choices=[('site', 'site'), ('client', 'client')], max_length=50, null=True)),
            ],
        ),
    ]
